/* Negotiation Xpert — glossary & technique library (English / Spanish).
   All explanations are original writing for this app.
   `inline` is the form used inside coach sentences; `against` marks tactics opponents use on you. */
(function (root) {
  'use strict';
  const NX = root.NX = root.NX || {};
  const L = (en, es) => ({ en, es });
  const T = (id, cat, name, inline, what, when, mistake, example, extra) =>
    Object.assign({ id, cat, name, inline: inline || name, what, when, mistake, example }, extra || {});

  const terms = [
    // ---------------- core techniques ----------------
    T('mirroring', 'core', L('Mirroring', 'Reflejo'), L('mirroring', 'reflejo'),
      L('Repeating the last one to three key words the other person said, usually as a gentle question. It signals that you are listening and prompts them to expand.',
        'Repetir las últimas una a tres palabras clave que dijo la otra persona, normalmente como una pregunta suave. Indica que escuchas y la invita a ampliar lo que dijo.'),
      L('When you want more information without steering the conversation, or when you need a moment to think.',
        'Cuando quieres más información sin dirigir la conversación, o cuando necesitas un momento para pensar.'),
      L('Repeating whole sentences or using it on every line. It starts to feel like a trick.',
        'Repetir frases completas o usarlo en cada intervención. Empieza a sentirse como un truco.'),
      L('They: "We need it done by Friday."  You: "By Friday?"', 'Ellos: «Lo necesitamos para el viernes». Tú: «¿Para el viernes?»'),
      { against: true }),
    T('labeling', 'core', L('Labeling', 'Etiquetado'), L('labeling', 'etiquetado'),
      L('Naming the emotion or situation you observe in the other person, starting with "It seems like", "It sounds like" or "It looks like". You describe; you do not judge.',
        'Nombrar la emoción o la situación que observas en la otra persona, empezando con «Parece que», «Suena como que» o «Da la impresión de que». Describes; no juzgas.'),
      L('When emotions are running high, when you sense hesitation, or to bring a hidden concern into the open.',
        'Cuando las emociones están a flor de piel, cuando notas dudas o para sacar a la luz una preocupación oculta.'),
      L('Saying "I think you feel..." or "I understand." It makes the statement about you instead of them.',
        'Decir «Creo que sientes…» o «Te entiendo». Eso pone el foco en ti en lugar de en la otra persona.'),
      L('"It sounds like you\'ve been burned by deals like this before."', '«Parece que ya te ha ido mal con acuerdos como este antes».'),
      { against: true }),
    T('calibrated', 'core', L('Calibrated questions', 'Preguntas calibradas'), L('calibrated question', 'pregunta calibrada'),
      L('Open questions that begin with "How" or "What". They cannot be answered with yes or no, and they invite the other side to think through your problem with you.',
        'Preguntas abiertas que empiezan con «Cómo» o «Qué». No se pueden responder con sí o no, e invitan a la otra parte a pensar contigo en tu problema.'),
      L('To gather information, to push back without saying no, or to make the other side consider your constraints.',
        'Para obtener información, para resistir sin decir que no o para que la otra parte considere tus limitaciones.'),
      L('Asking "Why?", which sounds accusatory, or asking closed questions such as "Is that your best price?"',
        'Preguntar «¿Por qué?», que suena acusatorio, o hacer preguntas cerradas como «¿Es su mejor precio?».'),
      L('"How am I supposed to do that?"  "What\'s the biggest obstacle on your side?"', '«¿Cómo se supone que haga eso?» «¿Cuál es el mayor obstáculo de tu lado?»'),
      { against: true }),
    T('noOriented', 'core', L('"No"-oriented questions', 'Preguntas orientadas al «no»'), L('"no"-oriented question', 'pregunta orientada al «no»'),
      L('Questions designed so the comfortable answer is "no". Saying no makes people feel safe and in control, so they relax and engage instead of defending themselves.',
        'Preguntas diseñadas para que la respuesta cómoda sea «no». Decir que no hace que la gente se sienta segura y con el control, así que se relaja y participa en lugar de defenderse.'),
      L('When you make a request or an offer, or when someone has gone quiet.', 'Cuando haces una petición o una oferta, o cuando alguien ha dejado de responder.'),
      L('Pushing for a "yes" early on. Forced yeses are often empty.', 'Buscar un «sí» demasiado pronto. Los síes forzados suelen estar vacíos.'),
      L('"Would it be a bad idea to revisit the timeline?"', '«¿Sería una mala idea revisar los plazos?»')),
    T('accusationAudit', 'core', L('Accusation audit', 'Auditoría de acusaciones'), L('accusation audit', 'auditoría de acusaciones'),
      L('Listing, out loud and before they can, the negative things the other person might think about you or your request. Saying them first takes away their sting.',
        'Enumerar en voz alta, antes de que lo haga la otra persona, las cosas negativas que podría pensar de ti o de tu petición. Decirlas primero les quita fuerza.'),
      L('At the start of a difficult conversation, or right before bad news or a low offer.', 'Al inicio de una conversación difícil, o justo antes de una mala noticia o una oferta baja.'),
      L('Being vague or following it with "but", which cancels everything you just said.', 'Ser vago o seguirlo con un «pero», que anula todo lo que acabas de decir.'),
      L('"You\'re probably going to think this offer is insulting, and that I don\'t value your work."', '«Probablemente vas a pensar que esta oferta es ofensiva y que no valoro tu trabajo».'),
      { against: true }),
    T('tacticalEmpathy', 'core', L('Tactical empathy', 'Empatía táctica'), L('tactical empathy', 'empatía táctica'),
      L('Deliberately understanding the other side\'s feelings and perspective, and showing them that you do. Understanding is not agreeing; it is information and influence.',
        'Comprender de forma deliberada las emociones y la perspectiva de la otra parte, y demostrárselo. Comprender no es estar de acuerdo; es información e influencia.'),
      L('Throughout the negotiation, and especially when the other side is upset or distrustful.', 'Durante toda la negociación, y sobre todo cuando la otra parte está molesta o desconfía.'),
      L('Confusing it with sympathy or giving in. You can understand someone fully and still hold your position.',
        'Confundirla con compasión o con ceder. Puedes comprender a alguien por completo y aun así mantener tu posición.'),
      L('"It seems like this deadline has put your whole team under pressure."', '«Parece que esta fecha límite ha puesto a todo tu equipo bajo presión».')),
    T('thatsRight', 'core', L('"That\'s right"', '«Así es»'), L('“that’s right”', '«así es»'),
      L('The moment the other person says "That\'s right" after you summarize their situation. It signals they feel genuinely understood, which is when real movement happens. "You\'re right" is different: it often means "please stop talking".',
        'El momento en que la otra persona dice «Así es» después de que resumes su situación. Indica que se siente verdaderamente comprendida, y es cuando se produce el avance real. «Tienes razón» es distinto: a menudo significa «deja de hablar».'),
      L('After you have uncovered their motives: summarize their view and feelings, then pause.', 'Después de descubrir sus motivos: resume su punto de vista y sus emociones, y haz una pausa.'),
      L('Summarizing only facts, or summarizing your own position instead of theirs.', 'Resumir solo hechos, o resumir tu propia posición en lugar de la suya.'),
      L('"So what matters most is not the money itself, it\'s feeling respected after how the last deal went."', '«Entonces lo que más importa no es el dinero en sí, sino sentirte respetado después de cómo salió el último acuerdo».')),
    T('summary', 'core', L('Summarizing', 'Resumen'), L('summary', 'resumen'),
      L('Restating, in your own words, what the other person has told you, including how they feel about it. It is the tool that produces "That\'s right".',
        'Reformular con tus palabras lo que te ha dicho la otra persona, incluido cómo se siente al respecto. Es la herramienta que produce el «Así es».'),
      L('Once you understand their situation and motives, and before you make your key request.', 'Cuando entiendes su situación y sus motivos, y antes de hacer tu petición clave.'),
      L('Rushing it before you know what really matters to them.', 'Hacerlo con prisa, antes de saber qué les importa de verdad.'),
      L('"Let me make sure I understand: you need a quick sale because the move is already booked."', '«Déjame ver si entiendo: necesitas vender rápido porque la mudanza ya está programada».')),
    T('effectivePause', 'core', L('Effective pause', 'Pausa eficaz'), L('effective pause', 'pausa eficaz'),
      L('Staying deliberately silent after a label, a question or an offer. Silence gives the other side room to fill the gap, often with useful information or a concession.',
        'Guardar silencio a propósito después de una etiqueta, una pregunta o una oferta. El silencio da espacio a la otra parte para llenarlo, a menudo con información útil o una concesión.'),
      L('Right after you ask something important or name a number.', 'Justo después de preguntar algo importante o dar una cifra.'),
      L('Filling the silence yourself by explaining, justifying or improving your offer.', 'Llenar tú el silencio explicando, justificando o mejorando tu oferta.'),
      L('"It sounds like the timing is difficult." (then wait)', '«Parece que el momento es complicado». (y esperas)')),

    // ---------------- bargaining ----------------
    T('ackerman', 'bargain', L('Ackerman bargaining', 'Método Ackerman'), L('Ackerman bargaining', 'método Ackerman'),
      L('A planned offer sequence. Set your target, open at 65% of it, then move to 85%, 95% and finally 100%, ending on a precise, non-round number. The shrinking steps signal you are reaching your limit. (For a selling position, mirror it: open well above your target and come down in shrinking steps.)',
        'Una secuencia de ofertas planificada. Fija tu objetivo, abre con el 65 %, luego sube al 85 %, al 95 % y por último al 100 %, terminando con una cifra precisa y no redonda. Los pasos decrecientes indican que llegas a tu límite. (Si vendes, invierte el orden: abre bastante por encima de tu objetivo y baja con pasos cada vez menores.)'),
      L('When you are bargaining over a price or amount and have already built rapport.', 'Cuando negocias un precio o una cantidad y ya has generado sintonía.'),
      L('Making equal or growing jumps, or ending on a round number.', 'Hacer saltos iguales o crecientes, o terminar en una cifra redonda.'),
      L('Target $1,000: offer $650, then $850, then $950, then $997.', 'Objetivo 1.000 $: ofrece 650, luego 850, luego 950 y después 997.')),
    T('anchoring', 'bargain', L('Anchoring', 'Anclaje'), L('anchoring', 'anclaje'),
      L('Putting the first number on the table to set the reference point. People adjust from an anchor, so the first figure shapes the whole negotiation.',
        'Poner la primera cifra sobre la mesa para fijar el punto de referencia. La gente se ajusta a partir del ancla, así que la primera cifra condiciona toda la negociación.'),
      L('When you know the market well. If you are unsure, let the other side anchor first and use calibrated questions.',
        'Cuando conoces bien el mercado. Si no estás seguro, deja que la otra parte ancle primero y usa preguntas calibradas.'),
      L('Being anchored by the other side and negotiating only around their number.', 'Dejarte anclar por la otra parte y negociar solo alrededor de su cifra.'),
      L('"Similar projects usually come in between $9,000 and $11,000."', '«Proyectos similares suelen estar entre 9.000 y 11.000 $».'),
      { against: true }),
    T('extremeAnchor', 'bargain', L('Extreme anchor', 'Anclaje extremo'), L('extreme anchor', 'anclaje extremo'),
      L('An opening number far beyond what is reasonable, meant to drag the midpoint toward one side.', 'Una cifra de apertura muy alejada de lo razonable, pensada para arrastrar el punto medio hacia un lado.'),
      L('Rarely. When used against you, do not counter it; label it and ask how they arrived at it.', 'Rara vez. Si la usan contra ti, no la contraofertes; etiquétala y pregunta cómo llegaron a ella.'),
      L('Responding with your own extreme number, which turns the talk into a contest.', 'Responder con tu propia cifra extrema, lo que convierte la conversación en un pulso.'),
      L('"It seems like that number is based on something I\'m not seeing. How did you arrive at it?"', '«Parece que esa cifra se basa en algo que no estoy viendo. ¿Cómo llegaste a ella?»'),
      { against: true }),
    T('preciseNumber', 'bargain', L('Precise number', 'Número preciso'), L('precise number', 'número preciso'),
      L('A non-round figure such as $4,863 instead of $5,000. It sounds calculated and final, so people push back on it less.',
        'Una cifra no redonda, como 4.863 $ en lugar de 5.000 $. Suena calculada y definitiva, así que la gente la discute menos.'),
      L('For your final offer, especially the last step of Ackerman bargaining.', 'En tu oferta final, sobre todo en el último paso del método Ackerman.'),
      L('Using precise numbers early, which can make you look rigid before trust exists.', 'Usar cifras precisas demasiado pronto, lo que puede hacerte parecer rígido antes de que haya confianza.'),
      L('"I can do $2,388. That\'s truly everything in my budget."', '«Puedo llegar a 2.388 $. De verdad es todo mi presupuesto».')),
    T('concession', 'bargain', L('Concession', 'Concesión'), L('concession', 'concesión'),
      L('Something you give up or improve to move toward agreement: price, timing, terms or extras.', 'Algo que cedes o mejoras para acercarte al acuerdo: precio, plazos, condiciones o extras.'),
      L('Deliberately, in shrinking amounts, and ideally in exchange for something.', 'De forma deliberada, en cantidades decrecientes y, a ser posible, a cambio de algo.'),
      L('Conceding to fill a silence or because of pressure, without getting anything back.', 'Ceder para llenar un silencio o por presión, sin recibir nada a cambio.'),
      L('"If you can start next week, I can be flexible on the deposit."', '«Si puedes empezar la próxima semana, puedo ser flexible con el anticipo».')),
    T('batna', 'concepts', L('BATNA', 'MAAN (BATNA)'), L('BATNA', 'MAAN (BATNA)'),
      L('Your Best Alternative To a Negotiated Agreement: what you will do if this deal does not happen. A strong alternative gives you confidence to say no.',
        'Tu Mejor Alternativa a un Acuerdo Negociado: lo que harás si este acuerdo no sale. Una buena alternativa te da seguridad para decir que no.'),
      L('Know it before you start. It defines when walking away is better than agreeing.', 'Conócela antes de empezar. Define cuándo es mejor retirarte que aceptar.'),
      L('Bluffing about an alternative you do not have, or revealing a weak one.', 'Fingir una alternativa que no tienes, o revelar una débil.'),
      L('"I have another quote, but I\'d rather work with you if we can make the numbers fit."', '«Tengo otro presupuesto, pero prefiero trabajar contigo si logramos que los números encajen».')),
    T('reservationPrice', 'concepts', L('Reservation price', 'Precio de reserva'), L('reservation price', 'precio de reserva'),
      L('The worst deal you are willing to accept, your walk-away point. Every counterpart has one too, and it is usually hidden.',
        'El peor acuerdo que estás dispuesto a aceptar: tu punto de retirada. Toda contraparte tiene uno también, y suele estar oculto.'),
      L('Decide it before the negotiation so pressure in the moment cannot move it.', 'Decídelo antes de negociar para que la presión del momento no lo mueva.'),
      L('Revealing it, or treating it as your target.', 'Revelarlo, o tratarlo como tu objetivo.'),
      L('(Internal) "I will not pay more than $14,500 for this car."', '(Interno) «No pagaré más de 14.500 $ por este coche».')),
    T('zopa', 'concepts', L('ZOPA', 'ZOPA (zona de posible acuerdo)'), L('ZOPA', 'ZOPA'),
      L('The Zone Of Possible Agreement: the overlap between what each side is willing to accept. Deals can only happen inside it.',
        'La zona de posible acuerdo: el solapamiento entre lo que cada parte está dispuesta a aceptar. Solo hay acuerdo dentro de ella.'),
      L('Use questions to estimate where the other side\'s limits are.', 'Usa preguntas para estimar dónde están los límites de la otra parte.'),
      L('Assuming there is no zone because the opening positions are far apart.', 'Suponer que no hay zona porque las posiciones iniciales están muy alejadas.'),
      L('"What range were you hoping to land in?"', '«¿En qué rango esperabas cerrar?»')),
    T('leverage', 'concepts', L('Leverage', 'Poder de negociación'), L('leverage', 'poder de negociación'),
      L('Anything that makes the other side need the deal more or fear losing it: time pressure, alternatives, information, or something they want that only you can provide.',
        'Todo lo que hace que la otra parte necesite más el acuerdo o tema perderlo: la presión del tiempo, las alternativas, la información o algo que quiere y que solo tú puedes darle.'),
      L('Discover it through questions and listening; use it calmly, never as a threat.', 'Descúbrelo con preguntas y escuchando; úsalo con calma, nunca como amenaza.'),
      L('Overplaying it, which damages the relationship and invites retaliation.', 'Abusar de él, lo que daña la relación e invita a represalias.'),
      L('"It sounds like closing before the end of the month really matters to you."', '«Parece que cerrar antes de fin de mes te importa mucho».')),
    T('hiddenInformation', 'concepts', L('Hidden information', 'Información oculta'), L('hidden information', 'información oculta'),
      L('Facts the other side has not shared that change everything: a deadline, a debt, a fear, a boss to satisfy. Uncovering them is often the key to the whole negotiation.',
        'Hechos que la otra parte no ha compartido y que lo cambian todo: un plazo, una deuda, un miedo, un jefe al que satisfacer. Descubrirlos suele ser la clave de toda la negociación.'),
      L('Always look for them. Labels, mirrors and calibrated questions bring them out.', 'Búscala siempre. Las etiquetas, los reflejos y las preguntas calibradas la hacen salir.'),
      L('Talking so much that the other side never gets the chance to reveal anything.', 'Hablar tanto que la otra parte nunca tiene ocasión de revelar nada.'),
      L('"What\'s happening on your side that I might not know about?"', '«¿Qué está pasando de tu lado que quizás yo no sepa?»')),
    T('rapport', 'concepts', L('Rapport', 'Sintonía'), L('rapport', 'sintonía'),
      L('A working sense of trust and connection between both sides. With rapport, people share more and concede more easily.',
        'Una sensación práctica de confianza y conexión entre ambas partes. Con sintonía, la gente comparte más y cede con más facilidad.'),
      L('From the first sentence: tone, empathy and genuine curiosity build it.', 'Desde la primera frase: el tono, la empatía y la curiosidad genuina la construyen.'),
      L('Faking friendliness, which people detect quickly.', 'Fingir simpatía, algo que la gente detecta enseguida.'),
      L('"It seems like you really know this business inside out."', '«Parece que conoces este negocio al dedillo».')),
    T('proofOfLife', 'concepts', L('Proof of life', 'Prueba de vida'), L('proof of life', 'prueba de vida'),
      L('In kidnapping and extortion cases, verification that the person is alive and actually held by the caller, often through a question only they could answer.',
        'En casos de secuestro y extorsión, la verificación de que la persona está viva y realmente en poder de quien llama, a menudo con una pregunta que solo ella podría responder.'),
      L('Before any agreement in a crisis involving a captive, and immediately in a suspected scam call.', 'Antes de cualquier acuerdo en una crisis con una persona retenida, e inmediatamente ante una posible llamada fraudulenta.'),
      L('Skipping it under pressure, or asking a question the answer to which can be found online.', 'Omitirla por la presión, o hacer una pregunta cuya respuesta se puede encontrar en internet.'),
      L('"How do I know she\'s okay? Ask her what we named our first dog."', '«¿Cómo sé que está bien? Pregúntale cómo se llamaba nuestro primer perro».')),

    // ---------------- opponent tactics ----------------
    T('deadlinePressure', 'tactics', L('Deadline pressure', 'Presión por plazos'), L('deadline pressure', 'presión por plazos'),
      L('Using a real or invented deadline to rush you into a decision before you have thought it through. Fake deadlines are among the most common pressure tactics.',
        'Usar una fecha límite, real o inventada, para que decidas antes de pensarlo bien. Los plazos falsos están entre las tácticas de presión más comunes.'),
      L('Recognize it: when time pressure appears suddenly, slow down and test it.', 'Reconócela: cuando la presión del tiempo aparece de repente, ve más despacio y ponla a prueba.'),
      L('Accepting the deadline as fact and conceding to beat the clock.', 'Aceptar el plazo como un hecho y ceder para ganarle al reloj.'),
      L('Response: "It sounds like timing is critical for you. What happens if we need until Monday?"', 'Respuesta: «Parece que el tiempo es crucial para ti. ¿Qué pasa si necesitamos hasta el lunes?»'),
      { against: true }),
    T('takeItOrLeaveIt', 'tactics', L('Take it or leave it', 'Lo tomas o lo dejas'), L('“take it or leave it”', '«lo tomas o lo dejas»'),
      L('A final-sounding ultimatum meant to end the bargaining. It is frequently a bluff.', 'Un ultimátum con apariencia de definitivo, pensado para cortar el regateo. Con frecuencia es un farol.'),
      L('Recognize it and respond calmly rather than conceding or walking out on the spot.', 'Reconócelo y responde con calma en lugar de ceder o marcharte de inmediato.'),
      L('Taking it personally, or immediately raising your offer.', 'Tomártelo como algo personal, o subir tu oferta de inmediato.'),
      L('Response: "It seems like you feel you\'ve gone as far as you can. How am I supposed to make that work?"', 'Respuesta: «Parece que sientes que ya llegaste al máximo. ¿Cómo se supone que haga que eso funcione?»'),
      { against: true }),
    T('higherAuthority', 'tactics', L('Higher authority', 'Autoridad superior'), L('higher authority', 'autoridad superior'),
      L('Claiming someone else (a manager, partner or committee) must approve anything better, so they never have to concede directly.', 'Afirmar que otra persona (un jefe, un socio o un comité) debe aprobar cualquier mejora, para no tener que ceder directamente.'),
      L('Recognize it early; ask who else is involved and what they care about.', 'Reconócela pronto; pregunta quién más participa y qué le importa.'),
      L('Making your best offer to someone who cannot say yes.', 'Hacer tu mejor oferta a alguien que no puede decir que sí.'),
      L('Response: "What will your partner need to see to feel good about this?"', 'Respuesta: «¿Qué necesitará ver tu socio para sentirse bien con esto?»'),
      { against: true }),
    T('flinch', 'tactics', L('The flinch', 'El respingo'), L('flinch', 'respingo'),
      L('A visible, exaggerated reaction of shock to your number, designed to make you doubt it and concede.', 'Una reacción visible y exagerada de sorpresa ante tu cifra, pensada para que dudes de ella y cedas.'),
      L('Recognize it as theatre; stay quiet or label it.', 'Reconócelo como teatro; guarda silencio o etiquétalo.'),
      L('Rushing to justify or lower your offer.', 'Apresurarte a justificar o bajar tu oferta.'),
      L('Response: "It sounds like that number surprised you." (then pause)', 'Respuesta: «Parece que esa cifra te sorprendió». (y haces una pausa)'),
      { against: true }),
    T('nibble', 'tactics', L('Nibbling', 'Mordisqueo'), L('nibbling', 'mordisqueo'),
      L('Asking for small extras after the main terms seem settled, counting on you not wanting to reopen the deal.', 'Pedir pequeños extras cuando los términos principales parecen cerrados, contando con que no querrás reabrir el acuerdo.'),
      L('Recognize it near the close; trade rather than give.', 'Reconócelo cerca del cierre; intercambia en lugar de regalar.'),
      L('Saying yes to every small add-on to protect the deal.', 'Aceptar cada pequeño extra para proteger el acuerdo.'),
      L('Response: "I can look at that. What can you do on your side in return?"', 'Respuesta: «Puedo considerarlo. ¿Qué puedes hacer tú a cambio?»'),
      { against: true }),
    T('goodCopBadCop', 'tactics', L('Good cop, bad cop', 'Policía bueno, policía malo'), L('good cop, bad cop', 'policía bueno, policía malo'),
      L('One person plays the reasonable ally while blaming a tougher, absent or angry partner, so you concede to the "friend".', 'Una persona hace de aliado razonable mientras culpa a un socio más duro, ausente o enfadado, para que cedas ante el «amigo».'),
      L('Recognize that both roles serve the same side.', 'Reconoce que ambos papeles sirven al mismo lado.'),
      L('Treating the friendly one as your advocate.', 'Tratar al amable como si fuera tu defensor.'),
      L('Response: "It seems like you two see this differently. What would work for both of you?"', 'Respuesta: «Parece que ustedes dos lo ven distinto. ¿Qué funcionaría para ambos?»'),
      { against: true }),

    // ---------------- mistakes ----------------
    T('whyQuestions', 'mistakes', L('"Why" questions', 'Preguntas con «por qué»'), L('“why” questions', 'preguntas con «por qué»'),
      L('Questions starting with "Why" tend to sound like accusations and put people on the defensive, even when you are simply curious.', 'Las preguntas que empiezan con «por qué» suelen sonar a acusación y ponen a la gente a la defensiva, aunque solo sientas curiosidad.'),
      L('Avoid them. Turn them into "What" or "How" questions.', 'Evítalas. Conviértelas en preguntas con «qué» o «cómo».'),
      L('"Why is it so expensive?"', '«¿Por qué es tan caro?»'),
      L('Better: "What makes this the right price?"', 'Mejor: «¿Qué hace que este sea el precio adecuado?»')),
    T('splitDifference', 'mistakes', L('Splitting the difference', 'Partir la diferencia'), L('splitting the difference', 'partir la diferencia'),
      L('Offering to meet exactly halfway. It feels fair but rewards whoever opened most extreme, and usually means neither side gets what it needs.', 'Ofrecer quedar exactamente a mitad de camino. Parece justo, pero premia a quien abrió de forma más extrema y suele significar que nadie obtiene lo que necesita.'),
      L('Avoid it. Explore what each side actually needs instead.', 'Evítalo. Explora qué necesita realmente cada parte.'),
      L('"Let\'s just meet in the middle."', '«Quedemos en el medio y ya».'),
      L('Better: "How can we get closer to something that works for both of us?"', 'Mejor: «¿Cómo podemos acercarnos a algo que funcione para los dos?»')),
    T('aggressiveTone', 'mistakes', L('Aggressive tone', 'Tono agresivo'), L('aggressive tone', 'tono agresivo'),
      L('Insults, threats, demands or sarcasm. They trigger defensiveness and make the other side dig in, or walk away.', 'Insultos, amenazas, exigencias o sarcasmo. Provocan una actitud defensiva y hacen que la otra parte se atrinchere o se marche.'),
      L('Never. A calm, slow, curious tone is the most persuasive one.', 'Nunca. Un tono sereno, pausado y curioso es el más persuasivo.'),
      L('"That\'s ridiculous. You\'re ripping me off."', '«Eso es ridículo. Me estás estafando».'),
      L('Better: "It seems like we see the value very differently."', 'Mejor: «Parece que valoramos esto de forma muy distinta».')),
    T('raisingTooQuickly', 'mistakes', L('Raising your offer too quickly', 'Subir tu oferta demasiado rápido'), L('raising your offer too quickly', 'subiendo tu oferta demasiado rápido'),
      L('Making large or rapid concessions, often to fill a silence. It tells the other side there is plenty more room.', 'Hacer concesiones grandes o rápidas, a menudo para llenar un silencio. Le dice a la otra parte que queda mucho margen.'),
      L('Avoid it. Move in planned, shrinking steps.', 'Evítalo. Muévete en pasos planificados y decrecientes.'),
      L('Going from $500 to $800 in one move without them giving anything.', 'Pasar de 500 a 800 $ de una vez sin que la otra parte ceda nada.'),
      L('Better: hold your number and ask "How am I supposed to do that?"', 'Mejor: sostén tu cifra y pregunta «¿Cómo se supone que haga eso?»')),
    T('yesTooFast', 'mistakes', L('Saying yes too fast', 'Decir que sí demasiado rápido'), L('saying yes too fast', 'decir que sí demasiado rápido'),
      L('Accepting the first offer or agreeing before exploring. It leaves value on the table and can make the other side regret their price.', 'Aceptar la primera oferta o estar de acuerdo antes de explorar. Deja valor sobre la mesa y puede hacer que la otra parte se arrepienta de su precio.'),
      L('Avoid it. Even a good first offer deserves one calibrated question.', 'Evítalo. Incluso una buena primera oferta merece una pregunta calibrada.'),
      L('"Sure, sounds good!" to their opening number.', '«¡Claro, me parece bien!» ante su cifra inicial.'),
      L('Better: "That\'s close. How can we make it work a little better for me?"', 'Mejor: «Estamos cerca. ¿Cómo podemos hacer que funcione un poco mejor para mí?»'))
  ];

  // Quiz ids used by the engine map onto glossary entries
  const alias = { deadline: 'deadlinePressure' };
  const byId = {};
  terms.forEach(t => { byId[t.id] = t; });
  function get(id) { return byId[alias[id] || id]; }

  NX.glossary = { terms, get, categories: ['core', 'bargain', 'tactics', 'mistakes', 'concepts'] };
  if (typeof module !== 'undefined' && module.exports) module.exports = NX.glossary;
})(typeof window !== 'undefined' ? window : globalThis);
